#!/bin/bash
#SBATCH -N 1            # number of nodes on which to run
#SBATCH --gres=gpu:rtx6000:1        # number of gpus
#SBATCH --ntasks=8
#SBATCH --tasks-per-node=8
#SBATCH --cpus-per-task=4
#SBATCH --exclude="gpu138"
#SBATCH --time=7:00:00      # time limit
#SBATCH --mem=64GB         # minimum amount of real memory
#SBATCH --job-name=slotcon
#SBATCH --open-mode=append
#SBATCH --qos=scavenger
#SBATCH --signal=B:USR1@30

script=$1
params=$2

# trap handler - resubmit ourselves
handler()
{
        echo "function handler called at $(date)"	
	
	kill -SIGUSR1 "$child" 
	cd
        sbatch ~/SlotCon/slurm_scripts/job-atari "$script" "$params"
	echo $arc $dim_out $dim_hidden
}
# register signal handler
trap handler SIGUSR1
trap 'kill -SIGUSR1 "$child"' SIGTERM

echo $1 $2
cd ~/SlotCon
source ./venv/bin/activate

bash $script $params &
child=$!

wait "$child"
